---

- hosts: all
  become: yes
  tasks:

  - name: Check that the network interfaces are static
    shell: ip address | grep "inet 192."
    register: stdout
    changed_when: false

  - name: Print interfaces
    debug:
      msg: "{{ stdout.stdout_lines }}"

